/* eslint-disable import/prefer-default-export */
/* product actions */
export const GET_FEATURED_PRODUCTS = 'GET_FEATURED_PRODUCTS';
export const GET_FEATURED_PRODUCTS_SUCCESS = 'GET_FEATURED_PRODUCTS_SUCCESS';
export const GET_FEATURED_PRODUCTS_ERROR = 'GET_FEATURED_PRODUCTS_ERROR';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_ERROR = 'GET_ALL_PRODUCTS_ERROR';
