/* eslint-disable import/prefer-default-export */
/* product actions */
export const GET_FEATURED_PRODUCTS = 'GET_FEATURED_PRODUCTS';
export const GET_FEATURED_PRODUCTS_SUCCESS = 'GET_FEATURED_PRODUCTS_SUCCESS';
export const GET_FEATURED_PRODUCTS_ERROR = 'GET_FEATURED_PRODUCTS_ERROR';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_ERROR = 'GET_ALL_PRODUCTS_ERROR';
export const GET_ALL_PRODUCTS_IN_DEPARTMENT = 'GET_ALL_PRODUCTS_IN_DEPARTMENT';
export const GET_ALL_PRODUCTS_IN_DEPARTMENT_SUCCESS =
  'GET_ALL_PRODUCTS_IN_DEPARTMENT_SUCCESS';
export const GET_ALL_PRODUCTS_IN_DEPARTMENT_ERROR =
  'GET_ALL_PRODUCTS_IN_DEPARTMENT_ERROR';
export const GET_ALL_PRODUCTS_IN_CATEGORY = 'GET_ALL_PRODUCTS_IN_CATEGORY';
export const GET_ALL_PRODUCTS_IN_CATEGORY_SUCCESS =
  'GET_ALL_PRODUCTS_IN_CATEGORY_SUCCESS';
export const GET_ALL_PRODUCTS_IN_CATEGORY_ERROR =
  'GET_ALL_PRODUCTS_IN_CATEGORY_ERROR';
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS';
export const GET_PRODUCT_DETAILS_ERROR = 'GET_PRODUCT_DETAILS_ERROR';
